# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tweet.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tweet.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0btweet.proto\"C\n\x05Tweet\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05tweet\x18\x02 \x01(\t\x12\r\n\x05likes\x18\x03 \x01(\x05\x12\x10\n\x08location\x18\x04 \x01(\t\" \n\nSearchTerm\x12\x12\n\nsearchterm\x18\x01 \x01(\t\" \n\x06Tweets\x12\x16\n\x06tweets\x18\x01 \x03(\x0b\x32\x06.Tweet2V\n\tGetTweets\x12$\n\x0cSearchTweets\x12\x0b.SearchTerm\x1a\x07.Tweets\x12#\n\x0cSearchATweet\x12\x0b.SearchTerm\x1a\x06.Tweetb\x06proto3'
)




_TWEET = _descriptor.Descriptor(
  name='Tweet',
  full_name='Tweet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Tweet.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tweet', full_name='Tweet.tweet', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='likes', full_name='Tweet.likes', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='Tweet.location', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=82,
)


_SEARCHTERM = _descriptor.Descriptor(
  name='SearchTerm',
  full_name='SearchTerm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='searchterm', full_name='SearchTerm.searchterm', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=116,
)


_TWEETS = _descriptor.Descriptor(
  name='Tweets',
  full_name='Tweets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tweets', full_name='Tweets.tweets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=150,
)

_TWEETS.fields_by_name['tweets'].message_type = _TWEET
DESCRIPTOR.message_types_by_name['Tweet'] = _TWEET
DESCRIPTOR.message_types_by_name['SearchTerm'] = _SEARCHTERM
DESCRIPTOR.message_types_by_name['Tweets'] = _TWEETS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tweet = _reflection.GeneratedProtocolMessageType('Tweet', (_message.Message,), {
  'DESCRIPTOR' : _TWEET,
  '__module__' : 'tweet_pb2'
  # @@protoc_insertion_point(class_scope:Tweet)
  })
_sym_db.RegisterMessage(Tweet)

SearchTerm = _reflection.GeneratedProtocolMessageType('SearchTerm', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHTERM,
  '__module__' : 'tweet_pb2'
  # @@protoc_insertion_point(class_scope:SearchTerm)
  })
_sym_db.RegisterMessage(SearchTerm)

Tweets = _reflection.GeneratedProtocolMessageType('Tweets', (_message.Message,), {
  'DESCRIPTOR' : _TWEETS,
  '__module__' : 'tweet_pb2'
  # @@protoc_insertion_point(class_scope:Tweets)
  })
_sym_db.RegisterMessage(Tweets)



_GETTWEETS = _descriptor.ServiceDescriptor(
  name='GetTweets',
  full_name='GetTweets',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=152,
  serialized_end=238,
  methods=[
  _descriptor.MethodDescriptor(
    name='SearchTweets',
    full_name='GetTweets.SearchTweets',
    index=0,
    containing_service=None,
    input_type=_SEARCHTERM,
    output_type=_TWEETS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SearchATweet',
    full_name='GetTweets.SearchATweet',
    index=1,
    containing_service=None,
    input_type=_SEARCHTERM,
    output_type=_TWEET,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETTWEETS)

DESCRIPTOR.services_by_name['GetTweets'] = _GETTWEETS

# @@protoc_insertion_point(module_scope)
